name: Scheduled-Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  Post:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: make install-packages

      - name: Install dependencies
        run: make install-dependencies

      - name: Twitter
        id: twitter_status
        continue-on-error: true
        run: make twitter
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - name: Instagram
        id: instagram_status
        continue-on-error: true
        run: make instagram
        env:
          INSTAGRAM_BUSINESS_ACCOUNT_ID: ${{ secrets.INSTAGRAM_BUSINESS_ACCOUNT_ID }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}

      - name: Print output summmary
        run: echo '<table><tr><th>SNS</th><th>Result</th></tr><tr><td align="center">Instagram</td><td align="center">${{ steps.instagram_status.outcome }}</td></tr><tr><td align="center">Twitter</td><td align="center">${{ steps.twitter_status.outcome }}</td></tr></table>' >> $GITHUB_STEP_SUMMARY
