name: Scheduled Tweet

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 7-24/3 * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install chrome
      run: make install-chrome

    - name: Install necessary packages
      run: make install-twitter-requirements

    - name: Tweet
      run: python3 twitter.py
      env:
        CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
        CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
